### ISSUE TITLE
Error adding library to project

### ISSUE THREAD

**Issue by mesadri** [Armen101/AudioRecordView#14]
when I add AudioRecordView as my project dependencies, I got this error:
`Could not find androidx.appcompat:appcompat:1.2.0.
     Searched in the following locations:
       - https://jitpack.io/androidx/appcompat/appcompat/1.2.0/appcompat-1.2.0.pom
       - https://jitpack.io/androidx/appcompat/appcompat/1.2.0/appcompat-1.2.0.jar
       - https://dl.google.com/dl/android/maven2/androidx/appcompat/appcompat/1.2.0/appcompat-1.2.0.pom
       - https://dl.google.com/dl/android/maven2/androidx/appcompat/appcompat/1.2.0/appcompat-1.2.0.jar
       - https://jcenter.bintray.com/androidx/appcompat/appcompat/1.2.0/appcompat-1.2.0.pom
       - https://jcenter.bintray.com/androidx/appcompat/appcompat/1.2.0/appcompat-1.2.0.jar
       - https://repo.maven.apache.org/maven2/androidx/appcompat/appcompat/1.2.0/appcompat-1.2.0.pom
       - https://repo.maven.apache.org/maven2/androidx/appcompat/appcompat/1.2.0/appcompat-1.2.0.jar
     Required by:
         project :app > com.github.Armen101:AudioRecordView:1.0.5`

**Comment by Armen101** [comment]
Hi @mesadri. Thanks for your feedback. Please send additional information, such as dependencies list, target version, etc.

**Comment by Armen101** [comment]
The user didn't provide enough information.

**Comment by shobanavelmurugan** [comment]
I got this error 
**Could not find com.github.Armen101:AudioRecordView:1.0.5.**
Required by:
    project :app
Search in build.gradle files

Added the module/gradle file dependency
   //Audio visualizer
    **implementation 'com.github.Armen101:AudioRecordView:1.0.5'**

Note: My compileSDKVersion 32 please upgrade your library
