### ISSUE TITLE
@Armen101 I think there is no option available for stopping it's horizontal movement .

### ISSUE THREAD

**Issue by SomnathS09** [Armen101/AudioRecordView#17]
@Armen101 I think there is no option available for stopping it's horizontal movement .
Hence, please reopen this issue

_Originally posted by @SomnathS09 in https://github.com/Armen101/AudioRecordView/issues/16#issuecomment-894755000_

**Comment by Armen101** [comment]
Actually, the library is not for what you want but you can minimize AudioRecordView's width. for me work with 8dp.

https://user-images.githubusercontent.com/26878699/128626180-bf2cee74-e2fd-4b1c-aae9-320a8d0929e8.mp4

just set 

 <com.visualizer.amplitude.AudioRecordView
        android:layout_width="8dp"
