### ISSUE TITLE
Support drawing waves for playback 

### ISSUE THREAD

**Issue by kazemihabib** [Armen101/AudioRecordView#6]
Thanks for your nice library
At the moment AudioRecordView removes previous data when the new data came and there is no space. But I think it would be a good idea to keep the old data and scroll horizontally the you can also use it to show the progress of playback.
you can fill the wave bars with another color like how telegram do that on playing voices:
https://telegram.org/file/811140497/169b/cbXkJ0EYq8I.90727/d8b1bbc78a215054df
(Actually telegram not shows this UI on voice record it shows that on playback)

**Comment by Armen101** [comment]
@kazemihabib thanks for the issue. I understand, but I think that these are different views with a different logic and use, and I am pleased to inform you that I have already created this custom view (VisualizerView). You gave me a good idea and you will be sure that I will prepare a new library and share it. Thank you.

**Comment by kazemihabib** [comment]
@Armen101 Thank you, that would be great.
