### ISSUE TITLE
update not working properly

### ISSUE THREAD

**Issue by amirreza-sobhdel** [Armen101/AudioRecordView#7]
with shorter intervals of updating, the view fails to show the right amplitude

**Comment by Armen101** [comment]
Hi @amirreza-sobhdel . Thanks for your feedback. Please send additional information about the issue

Device model -
Interval - 
Which concept do you use for iteration ? Timer Task, Handler, loops, Rx functions etc..

**Comment by Armen101** [comment]
Is Strong advice/rule - minimum update interval must be not smaller than 50 milliseconds.
