### ISSUE TITLE
How to change direction

### ISSUE THREAD

**Issue by wwwgaoxi** [Armen101/AudioRecordView#9]
How to change direction? chunkX is not easy to change

**Comment by Armen101** [comment]
Hi @wwwgaoxi . What do you mean by "direction"? You want to draw right to left or something else?

**Comment by wwwgaoxi** [comment]
Come in from the right and go all the way to the left without changing direction.

**Comment by Armen101** [comment]
Sorry, I didn't understand what you mean. Please attach any screenshots and additional information about the problem you are experiencing. Thanks.

**Comment by zaaach** [comment]
@Armen101 I think what he meant is that drawing the wave from the end of this view and then slide to left

**Comment by Armen101** [comment]
@wwwgaoxi I'm glad to inform you that AudioRecordView (1.0.5) already supports right-to-left drawing.
https://github.com/Armen101/AudioRecordView/releases/tag/1.0.5
